### ISSUE TITLE
Authentication fails

### ISSUE THREAD

**Issue by Ravenna** [jaredcobb/ccb-core#1]
I have tested the curl commands and also tested through a Curl Gui called Postman.  I am using the subdomain portion and my creds and get auth failures when I test connection.

**Comment by jaredcobb** [comment]
Can you provide any specific error messages that you're receiving?  The plugin should be telling you what specifically is failing (and what the CCB API failure response message is).

**Comment by Ravenna** [comment]
I am not sure, I was finally able to authenticate via curl yesterday and this morning I am able to auth through the plugin.  No issue.

thanks
