### ISSUE TITLE
Mapping to an existing post type

### ISSUE THREAD

**Issue by jordesign** [jaredcobb/ccb-core#12]
Hey Jared - I'm sorry to do this as an 'issue' but it seemed the best way I could find to ask a question...
I'm keen to map the CCB Event data to an existing post type

I have a hunch I can do it by filtering with 'ccb_core_synchronizer_post_api_map'
but I'm not certain how?

**Comment by jaredcobb** [comment]
Hi @jordesign,

You're correct, the `ccb_core_synchronizer_post_api_map` is how you'd map the events to your own custom post type. I've been meaning to write up a how-to guide in the wiki, but until then here's an example:

```php
function ccb_core_customize_post_api_map( $post_type_maps ) {
	$post_type_maps['custom_event'] = [
		'service' => 'public_calendar_listing',
		'data' => [
			'date_start' => date( 'Y-m-d', strtotime( '1 weeks ago' ) ),
			'date_end' => date( 'Y-m-d', strtotime( '+8 weeks' ) ),
		],
		'nodes' => [ 'items', 'item' ],
		'fields' => [
			'event_name' => 'post_title',
			'event_description' => 'post_content',
			'date' => 'post_meta',
			'start_time' => 'post_meta',
			'end_time' => 'post_meta',
			'event_duration' => 'post_meta',
			'location' => 'post_meta',
		],
	];
	return $post_type_maps;
}
add_filter( 'ccb_core_synchronizer_post_api_map', 'ccb_core_customize_post_api_map' );
```

In this case `custom_event` would be the slug of **your** existing custom post type. If you need to also synchronize any custom taxonomies (i.e. group names or event types), you can use the `ccb_core_synchronizer_taxonomy_api_map` filter in a similar way.

**Comment by jordesign** [comment]
Oh that's so awesome - thanks Jared.
My one remaining question (therefore) is in terms of mapping the fields to an existing meta field...
particularly the start_date and end_date

instead of `'date' => 'post_meta',`
is there a way i can assign it to a specific post_meta field?

`'date' => 'post_meta('my_date_field')',` or something?

**Comment by jaredcobb** [comment]
Yep, in that case there's an _additional_ filter you can use. It's called `ccb_core_synchronizer_insert_post_args` and it essentially filters the `$postarr` array that [`wp_insert_post`](https://developer.wordpress.org/reference/functions/wp_insert_post/) uses.

Here's a complete example:

```php
function ccb_core_customize_post_api_map( $post_type_maps ) {
	$post_type_maps['custom_event'] = [
		'service' => 'public_calendar_listing',
		'data' => [
			'date_start' => date( 'Y-m-d', strtotime( '1 weeks ago' ) ),
			'date_end' => date( 'Y-m-d', strtotime( '+8 weeks' ) ),
		],
		'nodes' => [ 'items', 'item' ],
		'fields' => [
			'event_name' => 'post_title',
			'event_description' => 'post_content',
		],
	];
	return $post_type_maps;
}
add_filter( 'ccb_core_synchronizer_post_api_map', 'ccb_core_customize_post_api_map' );

function ccb_core_customize_insert_post_args( $args, $entity, $settings, $post_type ) {
	if (
		'custom_event' === $post_type
		&& ! empty( $entity->date )
		&& ! empty( $entity->location )
	) {
		$args['meta_input']['my_date_field'] = (string) $entity->date;
		$args['meta_input']['my_location_field'] = (string) $entity->location;
	}
	return $args;
}
add_filter( 'ccb_core_synchronizer_insert_post_args', 'ccb_core_customize_insert_post_args', 10, 4 );
```

- I removed the `post_meta` mappings from the `ccb_core_customize_post_api_map`
- The `ccb_core_customize_insert_post_args` provides you with the entire event object called `$entity` so if the node value exists in the XML, it'll be a property here.
- It's best to ensure they're not empty before trying to use them so that you don't throw any errors.

**Comment by jaredcobb** [comment]
@jordesign Feel free to re-open if you have any problems with those snippets.

**Comment by jordesign** [comment]
Thank @jaredcobb that looks so awesome - I'm going to give it a try :)
