### ISSUE TITLE
main_leader information missing from Admin UI

### ISSUE THREAD

**Issue by tamala73** [jaredcobb/ccb-core#23]
When I perform a group sync with the setting to 'Show In Admin UI?' I am not seeing the custom fields leader_full_name and leader_email.

**Comment by jaredcobb** [comment]
Hi @tamala73 

The "Show In Admin UI" is a setting meant to allow your Groups and their _taxonomies_ to be viewable in the menu like so:

![screen shot 2019-01-06 at 9 09 09 am](https://user-images.githubusercontent.com/329077/50738597-ebc58a80-1192-11e9-8ba9-5fda0e98cccc.png)

However additional fields (that are not necessarily shared across all groups) are stored as something called Post Meta (aka Custom Fields).

Here's a bit more info on how various types of data get stored: https://github.com/jaredcobb/ccb-core/wiki/CCB-Entities

I recommend installing a plugin called Post Meta Inspector https://wordpress.org/plugins/post-meta-inspector/ which allows you to see that info direct in a Group's page (but only in the admin).

If you need to _output_ post meta in your template, you would use the native WordPress function https://developer.wordpress.org/reference/functions/get_post_meta/

Finally, here's a good doc on Post Meta (aka Custom Fields) that has a lot of great info: https://codex.wordpress.org/Custom_Fields

**Comment by tamala73** [comment]
Thanks!
