### ISSUE TITLE
has this plugin been abandoned?

### ISSUE THREAD

**Issue by jough74** [jaredcobb/ccb-core#29]
I'm wondering if the plugin author is still supporting and updating this very useful plugin.

anyone?

**Comment by jaredcobb** [comment]
@jough74 No, but I've been away from this project this year. I'm planning to release some updates over the next few weeks to address several issues. I do have version 1.0.8 that can be downloaded from here (and manually installed) https://github.com/jaredcobb/ccb-core/archive/master.zip which fixes a common issue with password encryption for several users. If you'd like to test and let me know if you have any problems I'd love to hear about it. Thanks.

**Comment by jough74** [comment]
Very glad to hear it. Thank you Jared. Your plugin provides a critical piece of the solution I've adopted to help our church members get plugged into community and grow in their faith. We appreciate your work to keep it updated. If you charged a fee or accepted donations, I for one, would think it is worth supporting.

**Comment by jaredcobb** [comment]
@jough74 Thanks! I appreciate that. I decided to intentionally not monetize or take donations for a couple of reasons:

1. I can only provide very limited support and only in my spare time. I would feel bad accepting money and then not providing quality support.
2. There's a great paid plugin called CCBPress https://ccbpress.com/ that I would recommend to anyone who's willing to pay for a premium plugin and also get great support.

I appreciate the kind words!
