### ISSUE TITLE
Import Event Image as Post Thumbnail

### ISSUE THREAD

**Issue by nicholaspetersen** [jaredcobb/ccb-core#4]
Just wondering if there is a way to add support for importing event images as post thumbnails the way groups do. This could be very helpful!
Thanks!

**Comment by jaredcobb** [comment]
I've added an example on how this would be accomplished using the 1.0.0 version of the plugin here https://github.com/jaredcobb/ccb-core/wiki/Download-&-Attach-Event-Images
